version: '3.4'

services:
  backend:
    build: backend
    volumes:
      - ./backend:/app:cached
    working_dir: /app
    env_file:
      - ./.env.dist
      - ./.env
    entrypoint: ./entrypoint.sh
