version: '3.4'

services:
  backend:
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=${DATABASE_NAME}"
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
    ports:
      - 5432:5432

volumes:
  database-data:
