# Generated by Django 3.2.8 on 2022-02-03 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Write',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='Ручной идентификатор пользователя')),
                ('step', models.CharField(choices=[('two', 'Первый шаг'), ('two', 'Второй шаг'), ('finish', 'Финиш')], max_length=64, verbose_name='Какой опрос проходит пользователь')),
                ('cats', models.IntegerField(default=0, verbose_name='Количество съеденных котов')),
                ('breads', models.IntegerField(default=0, verbose_name='Количество съеденного хлеба')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['key', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст сообщения')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ на сообщение')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.message', verbose_name='Предыдущее сообщение')),
                ('write', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.write', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['write', 'id'],
            },
        ),
    ]

