# Generated by Django 3.2.8 on 2022-02-10 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='Ручной идентификатор')),
                ('step', models.CharField(choices=[('start', 'Старт'), ('form', 'Форма объекта'), ('ears', 'Наличие у объекта ушей'), ('end_cat', 'Конец, кот определен'), ('end_bread', 'Конец, хлеб определен')], default='start', max_length=128, verbose_name='На каком этапе диалога')),
                ('cats', models.IntegerField(default=0, verbose_name='Количество съеденных котов')),
                ('breads', models.IntegerField(default=0, verbose_name='Количество съеденного хлеба')),
            ],
            options={
                'verbose_name': 'Отправитель',
                'verbose_name_plural': 'Отправители',
                'ordering': ['key', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст сообщения')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ на сообщение')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.message', verbose_name='Предыдущее сообщение')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.sender', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['sender', 'id'],
            },
        ),
    ]
